package com.song.coinpc.common.enums;

import java.util.Arrays;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum MarketType {
    BTC("BTC", "비트코인"),
    ETH("ETH", "이더리움"),
    NEO("NEO", "네오"),
    MTL("MTL", "메탈"),
    XRP("XRP", "리플"),
    ETC("ETC", "이더리움클래식"),
    OMG("OMG", "오미세고"),
    SNT("SNT", "스테이터스네트워크토큰"),
    WAVES("WAVES", "웨이브"),
    XEM("XEM", "넴"),
    QTUM("QTUM", "퀀텀"),
    LSK("LSK", "리스크"),
    STEEM("STEEM", "스팀"),
    XLM("XLM", "스텔라루멘"),
    ARDR("ARDR", "아더"),
    ARK("ARK", "아크"),
    STORJ("STORJ", "스토리지"),
    GRS("GRS", "그로스톨코인"),
    REP("REP", "어거"),
    ADA("ADA", "에이다"),
    SBD("SBD", "스팀달러"),
    POWR("POWR", "파워렛저"),
    BTG("BTG", "비트코인골드"),
    ICX("ICX", "아이콘"),
    EOS("EOS", "이오스"),
    TRX("TRX", "트론"),
    SC("SC", "시아코인"),
    ONT("ONT", "온톨로지"),
    ZIL("ZIL", "질리카"),
    POLY("POLY", "폴리매쓰"),
    ZRX("ZRX", "제로엑스"),
    LOOM("LOOM", "룸네트워크"),
    BCH("BCH", "비트코인캐시"),
    BAT("BAT", "베이직어텐션토큰"),
    IOST("IOST", "아이오에스티"),
    RFR("RFR", "리퍼리움"),
    CVC("CVC", "시빅"),
    IQ("IQ", "아이큐"),
    IOTA("IOTA", "아이오타"),
    MFT("MFT", "메인프레임"),
    ONG("ONG", "온톨로지가스"),
    GAS("GAS", "가스"),
    UPP("UPP", "센티넬프로토콜"),
    ELF("ELF", "엘프"),
    KNC("KNC", "카이버네트워크"),
    BSV("BSV", "비트코인에스브이"),
    THETA("THETA", "쎄타토큰"),
    QKC("QKC", "쿼크체인"),
    BTT("BTT", "비트토렌트"),
    MOC("MOC", "모스코인"),
    ENJ("ENJ", "엔진코인"),
    TFUEL("TFUEL", "쎄타퓨엘"),
    MANA("MANA", "디센트럴랜드"),
    ANKR("ANKR", "앵커"),
    AERGO("AERGO", "아르고"),
    ATOM("ATOM", "코스모스"),
    TT("TT", "썬더코어"),
    CRE("CRE", "캐리프로토콜"),
    MBL("MBL", "무비블록"),
    WAXP("WAXP", "왁스"),
    HBAR("HBAR", "헤데라"),
    MED("MED", "메디블록"),
    MLK("MLK", "밀크"),
    STPT("STPT", "에스티피"),
    ORBS("ORBS", "오브스"),
    VET("VET", "비체인"),
    CHZ("CHZ", "칠리즈"),
    STMX("STMX", "스톰엑스"),
    DKA("DKA", "디카르고"),
    HIVE("HIVE", "하이브"),
    KAVA("KAVA", "카바"),
    AHT("AHT", "아하토큰"),
    LINK("LINK", "체인링크"),
    XTZ("XTZ", "테조스"),
    BORA("BORA", "보라"),
    JST("JST", "저스트"),
    CRO("CRO", "크로노스"),
    TON("TON", "톤"),
    SXP("SXP", "솔라"),
    HUNT("HUNT", "헌트"),
    PLA("PLA", "플레이댑"),
    DOT("DOT", "폴카닷"),
    SRM("SRM", "세럼"),
    MVL("MVL", "엠블"),
    STRAX("STRAX", "스트라티스"),
    AQT("AQT", "알파쿼크"),
    GLM("GLM", "골렘"),
    SSX("SSX", "썸씽"),
    META("META", "메타디움"),
    FCT2("FCT2", "피르마체인"),
    CBK("CBK", "코박토큰"),
    SAND("SAND", "샌드박스"),
    HUM("HUM", "휴먼스케이프"),
    DOGE("DOGE", "도지코인"),
    STRK("STRK", "스트라이크"),
    PUNDIX("PUNDIX", "펀디엑스"),
    FLOW("FLOW", "플로우"),
    DAWN("DAWN", "던프로토콜"),
    AXS("AXS", "엑시인피니티"),
    STX("STX", "스택스"),
    XEC("XEC", "이캐시"),
    SOL("SOL", "솔라나"),
    MATIC("MATIC", "폴리곤"),
    NU("NU", "누사이퍼"),
    AAVE("AAVE", "에이브"),
    INCH1("1INCH", "1인치네트워크"),
    ALGO("ALGO", "알고랜드"),
    NEAR("NEAR", "니어프로토콜"),
    WEMIX("WEMIX", "위믹스"),
    AVAX("AVAX", "아발란체"),
    T("T", "쓰레스홀드"),
    CELO("CELO", "셀로"),
    GMT("GMT", "스테픈"),
    APT("APT", "앱토스"),
    NOT_KNOWN("NOT_KNOWN", "")
    ;

    private final String code;
    private final String koreanName;

    public static MarketType from(String code) {

        return Arrays.stream(values())
                     .filter(it -> it.getCode().equals(code))
                     .findFirst()
                     .orElse(NOT_KNOWN);
    }
}
