on:
  push:
    branches:
      - main

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: Run a one-line script     # Runs a single command using the runners shell
        run: echo Hello, world!
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        
      - name: Move jar file
        run: cp -f ./build/libs/*-SNAPSHOT.jar ./deploy
        shell: bash
        
      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip ./deploy
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://coinpc-deploy/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name coinpc --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name coinpc-main --s3-location bucket=coinpc-deploy,bundleType=zip,key=$GITHUB_SHA.zip

      - name: curl for test
        uses: wei/curl@master
        with:
          args: http://ec2-3-34-124-201.ap-northeast-2.compute.amazonaws.com:9918/test



